### ISSUE TITLE
Need absolute path option for location of "vcs".

### ISSUE THREAD

**Issue by steveupham** [fangism/hackt#38]
Need absolute path option for location of "vcs".

**Comment by fangism** [comment]
I committed another patch to follow that applies the same fix to the example Makefile used by installcheck in the test/prsim/vpi dir.

**Comment by steveupham** [comment]
Thanks.


Steve Upham
Senior CAD Engineer - Core Technology
Achronix Semiconductor Corporation

Work  : (408) 889 4151
Cell  : (408) 489 9468
Fax   : (408) 286 3645
Skype : steveusj
