### ISSUE TITLE
hacknet: support new device parameters NFIN and NF

### ISSUE THREAD

**Issue by teenylasers** [fangism/hackt#39]
Add parameters NFIN for number of fins in FinFET and NF for number of poly fingers. 

Currently, W is specified as the integer number of fins, then lambda is used to translate number of fins W to poly width W in nm for the netlist. Hacknet can either re-label W to NFIN in netlist, or redefine W and add NFIN in both ACT and spice.

**Comment by fangism** [comment]
This is in the [joydip15/hackt/tree/hac_finfet](https://github.com/joydip15/hackt/tree/hac_finfet) branch on his fork.  I'll take this as an official pull-request.  It looks like it could use some more test cases...
